// SQL curriculum data - portable ANSI-style SQL, with examples that work in
// PostgreSQL, SQLite, and most learning sandboxes.
export const sqlCurriculum = {
  label: "SQL",
  modules: [
    {
      id: "sql-module1",
      title: "Module 1 - Reading Data",
      duration: "50 min",
      lessons: [
        {
          id: "sql-module1-l1",
          title: "Your First SELECT Query",
          explanation: "SQL asks a database for information. SELECT names the columns you want, and FROM names the table that holds them. A query ends with a semicolon so the database knows where the statement stops.",
          concept: "SELECT column_name\nFROM table_name;\nSELECT reads data; it does not change it.",
          example: "SELECT name\nFROM students;",
          exercise: {
            prompt: "Write a query that returns every column from the books table.",
            starterCode: "-- Return every column from books\n",
            solution: "SELECT *\nFROM books;",
            tests: [{ type: "contains", value: "SELECT *" }, { type: "contains", value: "FROM books" }],
            debuggingTip: "Use * only when you truly want every column. It is handy while learning, but explicit column names are clearer in production queries.",
          },
        },
        {
          id: "sql-module1-l2",
          title: "Choosing Specific Columns",
          explanation: "Most queries need a few fields, not a whole row. List column names after SELECT and separate them with commas. The column order in SELECT becomes the order of the result.",
          concept: "SELECT title, author\nFROM books;\nCommas separate columns.",
          example: "SELECT title, published_year\nFROM books;",
          exercise: {
            prompt: "Return the name and email columns from customers.",
            starterCode: "-- Select two customer columns\n",
            solution: "SELECT name, email\nFROM customers;",
            tests: [{ type: "contains", value: "SELECT name, email" }, { type: "contains", value: "FROM customers" }],
            debuggingTip: "Do not put column names in quotes. Quotes make text values, while bare names refer to columns.",
          },
        },
        {
          id: "sql-module1-l3",
          title: "Renaming Results with AS",
          explanation: "AS gives a result column a temporary, readable name. It does not rename anything in the table. Aliases are especially useful when an expression would otherwise have an awkward heading.",
          concept: "SELECT price AS unit_price\nFROM products;\nAS changes the result label only.",
          example: "SELECT first_name AS customer_name\nFROM customers;",
          exercise: {
            prompt: "Return product_name from products, but label it item.",
            starterCode: "-- Add an alias\n",
            solution: "SELECT product_name AS item\nFROM products;",
            tests: [{ type: "contains", value: "product_name AS item" }, { type: "contains", value: "FROM products" }],
            debuggingTip: "The alias follows the existing column name. AS item product_name is backwards.",
          },
        },
        {
          id: "sql-module1-l4",
          title: "Removing Duplicates with DISTINCT",
          explanation: "A table can contain the same value many times. DISTINCT keeps one copy of each matching result, which is useful for answering questions such as which cities have customers.",
          concept: "SELECT DISTINCT city\nFROM customers;\nDISTINCT applies to the selected result.",
          example: "SELECT DISTINCT category\nFROM products;",
          exercise: {
            prompt: "List each distinct department from employees.",
            starterCode: "-- List departments once\n",
            solution: "SELECT DISTINCT department\nFROM employees;",
            tests: [{ type: "contains", value: "SELECT DISTINCT department" }, { type: "contains", value: "FROM employees" }],
            debuggingTip: "DISTINCT comes immediately after SELECT, before the column name.",
          },
        },
        {
          id: "sql-module1-l5",
          title: "Calculations in SELECT",
          explanation: "SQL can calculate values while it reads rows. Use arithmetic operators just as you would in a calculator, then give the expression an alias so the result makes sense to a human.",
          concept: "SELECT price * quantity AS line_total\nFROM order_items;\nExpressions can be selected like columns.",
          example: "SELECT salary * 12 AS annual_salary\nFROM employees;",
          exercise: {
            prompt: "Return price multiplied by quantity from order_items and call the result total.",
            starterCode: "-- Calculate each line total\n",
            solution: "SELECT price * quantity AS total\nFROM order_items;",
            tests: [{ type: "contains", value: "price * quantity" }, { type: "contains", value: "AS total" }],
            debuggingTip: "An expression needs no quotes. Write price * quantity, not 'price * quantity'.",
          },
        },
      ],
    },
    {
      id: "sql-module2",
      title: "Module 2 - Filtering and Sorting",
      duration: "60 min",
      lessons: [
        {
          id: "sql-module2-l1",
          title: "Filtering Rows with WHERE",
          explanation: "WHERE keeps only rows that meet a condition. It comes after FROM and before sorting or grouping. Text values use single quotes; numeric values do not.",
          concept: "SELECT columns\nFROM table\nWHERE condition;\nWHERE filters rows, not columns.",
          example: "SELECT name, price\nFROM products\nWHERE price > 20;",
          exercise: {
            prompt: "Return every column from orders where status is 'pending'.",
            starterCode: "-- Find pending orders\n",
            solution: "SELECT *\nFROM orders\nWHERE status = 'pending';",
            tests: [{ type: "contains", value: "FROM orders" }, { type: "contains", value: "WHERE status = 'pending'" }],
            debuggingTip: "Use a single equals sign for comparison in SQL, and single quotes around the text value pending.",
          },
        },
        {
          id: "sql-module2-l2",
          title: "Combining Conditions with AND and OR",
          explanation: "AND requires every condition to be true. OR accepts a row when at least one condition is true. Parentheses make mixed conditions easier to read and prevent accidental changes in meaning.",
          concept: "WHERE stock > 0 AND price < 50\nAND narrows; OR broadens.",
          example: "SELECT name\nFROM products\nWHERE category = 'Books' AND stock > 0;",
          exercise: {
            prompt: "Find employees in the Engineering department whose salary is greater than 80000.",
            starterCode: "-- Filter engineers by salary\n",
            solution: "SELECT *\nFROM employees\nWHERE department = 'Engineering' AND salary > 80000;",
            tests: [{ type: "contains", value: "department = 'Engineering'" }, { type: "contains", value: "AND salary > 80000" }],
            debuggingTip: "AND joins two complete conditions. Write department = 'Engineering' AND salary > 80000, not AND salary.",
          },
        },
        {
          id: "sql-module2-l3",
          title: "Finding Values in a Range",
          explanation: "BETWEEN checks an inclusive range, so both endpoints count. IN is cleaner than a long chain of OR conditions when you want one column to match any item in a short list.",
          concept: "WHERE price BETWEEN 10 AND 30\nWHERE city IN ('Moscow', 'Kazan')\nBETWEEN includes both ends.",
          example: "SELECT title\nFROM books\nWHERE published_year BETWEEN 2020 AND 2024;",
          exercise: {
            prompt: "Return products whose price is between 25 and 100, inclusive.",
            starterCode: "-- Filter a price range\n",
            solution: "SELECT *\nFROM products\nWHERE price BETWEEN 25 AND 100;",
            tests: [{ type: "contains", value: "price BETWEEN 25 AND 100" }],
            debuggingTip: "BETWEEN already includes its lower and upper bounds, so you do not need >= and <= here.",
          },
        },
        {
          id: "sql-module2-l4",
          title: "Matching Text with LIKE",
          explanation: "LIKE searches text patterns. The percent sign (%) means any number of characters, while underscore (_) means exactly one character. Use LIKE for patterns, not for exact matches.",
          concept: "WHERE name LIKE 'A%'\n% means any sequence of characters.\n_ means one character.",
          example: "SELECT name\nFROM customers\nWHERE email LIKE '%@example.com';",
          exercise: {
            prompt: "Find customers whose name starts with 'Ana'.",
            starterCode: "-- Match a name prefix\n",
            solution: "SELECT *\nFROM customers\nWHERE name LIKE 'Ana%';",
            tests: [{ type: "contains", value: "name LIKE 'Ana%'" }],
            debuggingTip: "Put the wildcard inside the quoted pattern. LIKE Ana% is not valid SQL.",
          },
        },
        {
          id: "sql-module2-l5",
          title: "Ordering and Limiting Results",
          explanation: "ORDER BY sorts results after filtering. ASC is the default direction, while DESC puts larger or newer values first. LIMIT is useful when you only need the first few rows.",
          concept: "ORDER BY created_at DESC\nLIMIT 5;\nSorting happens before limiting.",
          example: "SELECT title, rating\nFROM books\nORDER BY rating DESC\nLIMIT 3;",
          exercise: {
            prompt: "Return the five most expensive products.",
            starterCode: "-- Show the most expensive products first\n",
            solution: "SELECT *\nFROM products\nORDER BY price DESC\nLIMIT 5;",
            tests: [{ type: "contains", value: "ORDER BY price DESC" }, { type: "contains", value: "LIMIT 5" }],
            debuggingTip: "Write ORDER BY before LIMIT. Otherwise the database would have no instruction about which five rows matter.",
          },
        },
      ],
    },
    {
      id: "sql-module3",
      title: "Module 3 - Summaries and Groups",
      duration: "60 min",
      lessons: [
        {
          id: "sql-module3-l1",
          title: "Counting Rows",
          explanation: "COUNT turns many rows into one number. COUNT(*) counts rows, while COUNT(column_name) skips rows where that column is NULL. This small difference matters when data is incomplete.",
          concept: "SELECT COUNT(*) AS total\nFROM orders;\nCOUNT(*) counts rows.",
          example: "SELECT COUNT(*) AS customer_count\nFROM customers;",
          exercise: {
            prompt: "Count the rows in the tickets table and name the result ticket_count.",
            starterCode: "-- Count all tickets\n",
            solution: "SELECT COUNT(*) AS ticket_count\nFROM tickets;",
            tests: [{ type: "contains", value: "COUNT(*)" }, { type: "contains", value: "AS ticket_count" }],
            debuggingTip: "COUNT(*) has an asterisk inside parentheses. COUNT * is not valid syntax.",
          },
        },
        {
          id: "sql-module3-l2",
          title: "SUM, AVG, MIN, and MAX",
          explanation: "Aggregate functions summarize a column: SUM adds values, AVG finds an average, and MIN or MAX finds an extreme. They return one answer unless you group the rows first.",
          concept: "SUM(amount)\nAVG(price)\nMIN(date), MAX(date)\nAggregates summarize many rows.",
          example: "SELECT AVG(rating) AS average_rating\nFROM reviews;",
          exercise: {
            prompt: "Return the total amount from payments and call it total_revenue.",
            starterCode: "-- Sum all payments\n",
            solution: "SELECT SUM(amount) AS total_revenue\nFROM payments;",
            tests: [{ type: "contains", value: "SUM(amount)" }, { type: "contains", value: "AS total_revenue" }],
            debuggingTip: "SUM needs the column name in parentheses. It cannot add an entire table by itself.",
          },
        },
        {
          id: "sql-module3-l3",
          title: "Grouping Rows with GROUP BY",
          explanation: "GROUP BY makes one summary per distinct value. For example, you can count orders for each status instead of counting all orders together. Every selected non-aggregate column must appear in GROUP BY.",
          concept: "SELECT status, COUNT(*)\nFROM orders\nGROUP BY status;\nOne result row per group.",
          example: "SELECT department, AVG(salary) AS average_salary\nFROM employees\nGROUP BY department;",
          exercise: {
            prompt: "Count employees in each department.",
            starterCode: "-- Count each department\n",
            solution: "SELECT department, COUNT(*) AS employee_count\nFROM employees\nGROUP BY department;",
            tests: [{ type: "contains", value: "COUNT(*)" }, { type: "contains", value: "GROUP BY department" }],
            debuggingTip: "department appears in SELECT without an aggregate, so it must also appear in GROUP BY.",
          },
        },
        {
          id: "sql-module3-l4",
          title: "Filtering Groups with HAVING",
          explanation: "WHERE filters individual rows before grouping. HAVING filters the grouped results after an aggregate has been calculated. Use HAVING when your condition depends on COUNT, SUM, AVG, or another aggregate.",
          concept: "GROUP BY category\nHAVING COUNT(*) > 5\nHAVING filters groups.",
          example: "SELECT category, COUNT(*) AS product_count\nFROM products\nGROUP BY category\nHAVING COUNT(*) >= 10;",
          exercise: {
            prompt: "Show only departments that have more than 3 employees.",
            starterCode: "-- Keep larger departments\n",
            solution: "SELECT department, COUNT(*) AS employee_count\nFROM employees\nGROUP BY department\nHAVING COUNT(*) > 3;",
            tests: [{ type: "contains", value: "GROUP BY department" }, { type: "contains", value: "HAVING COUNT(*) > 3" }],
            debuggingTip: "COUNT(*) is calculated after rows are grouped, which is why this condition belongs in HAVING instead of WHERE.",
          },
        },
        {
          id: "sql-module3-l5",
          title: "Handling Missing Values with NULL",
          explanation: "NULL means a value is missing or unknown. It is not the same as zero or an empty string. Because NULL is unknown, compare it with IS NULL or IS NOT NULL rather than an equals sign.",
          concept: "WHERE shipped_at IS NULL\nWHERE email IS NOT NULL\nNever write = NULL.",
          example: "SELECT id, name\nFROM orders\nWHERE shipped_at IS NULL;",
          exercise: {
            prompt: "Find customers whose phone number is missing.",
            starterCode: "-- Find missing phone numbers\n",
            solution: "SELECT *\nFROM customers\nWHERE phone IS NULL;",
            tests: [{ type: "contains", value: "phone IS NULL" }],
            debuggingTip: "NULL is special in SQL. phone = NULL never matches because an unknown value cannot equal anything.",
          },
        },
      ],
    },
    {
      id: "sql-module4",
      title: "Module 4 - Joining Tables",
      duration: "70 min",
      lessons: [
        {
          id: "sql-module4-l1",
          title: "Why Tables Need Joins",
          explanation: "Databases split related facts into tables so information is not repeated. A foreign key such as orders.customer_id points to a row in customers. A JOIN lets one query read both sides of that relationship.",
          concept: "orders.customer_id → customers.id\nJOIN connects related rows.\nUse table.column when names could collide.",
          example: "SELECT orders.id, customers.name\nFROM orders\nJOIN customers ON orders.customer_id = customers.id;",
          exercise: {
            prompt: "Join orders to customers using orders.customer_id and customers.id.",
            starterCode: "-- Connect orders to their customers\n",
            solution: "SELECT orders.id, customers.name\nFROM orders\nJOIN customers ON orders.customer_id = customers.id;",
            tests: [{ type: "contains", value: "JOIN customers" }, { type: "contains", value: "ON orders.customer_id = customers.id" }],
            debuggingTip: "The ON condition states how the two tables relate. Do not compare unrelated columns just because they have similar names.",
          },
        },
        {
          id: "sql-module4-l2",
          title: "INNER JOIN",
          explanation: "An INNER JOIN returns only rows with a match on both sides. If an order points to no customer, that order is absent from the result. Plain JOIN usually means INNER JOIN.",
          concept: "INNER JOIN keeps matching pairs only.\nJOIN and INNER JOIN are equivalent in most SQL dialects.",
          example: "SELECT products.name, order_items.quantity\nFROM order_items\nINNER JOIN products ON order_items.product_id = products.id;",
          exercise: {
            prompt: "Use INNER JOIN to connect order_items to products through product_id.",
            starterCode: "-- Connect each order item to a product\n",
            solution: "SELECT order_items.quantity, products.name\nFROM order_items\nINNER JOIN products ON order_items.product_id = products.id;",
            tests: [{ type: "contains", value: "INNER JOIN products" }, { type: "contains", value: "order_items.product_id = products.id" }],
            debuggingTip: "Use qualified names such as products.id when both tables might contain an id column.",
          },
        },
        {
          id: "sql-module4-l3",
          title: "Keeping Unmatched Rows with LEFT JOIN",
          explanation: "A LEFT JOIN keeps every row from the table on the left, even when the right-hand table has no match. Missing right-side values appear as NULL, which makes LEFT JOIN useful for finding gaps.",
          concept: "FROM customers\nLEFT JOIN orders ...\nEvery customer remains in the result.",
          example: "SELECT customers.name, orders.id\nFROM customers\nLEFT JOIN orders ON customers.id = orders.customer_id;",
          exercise: {
            prompt: "List every customer and any matching order, keeping customers even when they have no orders.",
            starterCode: "-- Keep all customers\n",
            solution: "SELECT customers.name, orders.id\nFROM customers\nLEFT JOIN orders ON customers.id = orders.customer_id;",
            tests: [{ type: "contains", value: "LEFT JOIN orders" }, { type: "contains", value: "customers.id = orders.customer_id" }],
            debuggingTip: "The table you promise to keep goes before LEFT JOIN. Here, customers must be on the left.",
          },
        },
        {
          id: "sql-module4-l4",
          title: "Table Aliases",
          explanation: "Short table aliases make multi-table queries easier to scan. Define an alias after a table name, then use it consistently in SELECT, JOIN, and ON. Good aliases are brief but still recognizable.",
          concept: "FROM orders AS o\nJOIN customers AS c ON o.customer_id = c.id\nAliases shorten qualified names.",
          example: "SELECT o.id, c.name\nFROM orders AS o\nJOIN customers AS c ON o.customer_id = c.id;",
          exercise: {
            prompt: "Write the orders-to-customers join using o for orders and c for customers.",
            starterCode: "-- Use concise table aliases\n",
            solution: "SELECT o.id, c.name\nFROM orders AS o\nJOIN customers AS c ON o.customer_id = c.id;",
            tests: [{ type: "contains", value: "orders AS o" }, { type: "contains", value: "customers AS c" }, { type: "contains", value: "o.customer_id = c.id" }],
            debuggingTip: "Once you introduce an alias, use it. Mixing orders.customer_id with o.customer_id makes queries harder to maintain.",
          },
        },
        {
          id: "sql-module4-l5",
          title: "Finding Rows Without a Match",
          explanation: "LEFT JOIN plus IS NULL answers an important business question: which left-side rows have no related record? The join preserves every left row, then the NULL check isolates the missing matches.",
          concept: "LEFT JOIN orders ...\nWHERE orders.id IS NULL\nFind left-side rows with no match.",
          example: "SELECT customers.name\nFROM customers\nLEFT JOIN orders ON customers.id = orders.customer_id\nWHERE orders.id IS NULL;",
          exercise: {
            prompt: "Find customers who have never placed an order.",
            starterCode: "-- Find customers without orders\n",
            solution: "SELECT customers.name\nFROM customers\nLEFT JOIN orders ON customers.id = orders.customer_id\nWHERE orders.id IS NULL;",
            tests: [{ type: "contains", value: "LEFT JOIN orders" }, { type: "contains", value: "WHERE orders.id IS NULL" }],
            debuggingTip: "Use LEFT JOIN here. INNER JOIN removes unmatched customers before WHERE gets a chance to see them.",
          },
        },
      ],
    },
    {
      id: "sql-module5",
      title: "Module 5 - Changing Data Safely",
      duration: "70 min",
      lessons: [
        {
          id: "sql-module5-l1",
          title: "Adding Rows with INSERT",
          explanation: "INSERT creates a new row. Name the target columns explicitly so values cannot silently land in the wrong position when the table changes later.",
          concept: "INSERT INTO table (column_a, column_b)\nVALUES (value_a, value_b);\nList columns explicitly.",
          example: "INSERT INTO customers (name, email)\nVALUES ('Mina Lee', 'mina@example.com');",
          exercise: {
            prompt: "Add a product named 'Notebook' with a price of 12.50 to products.",
            starterCode: "-- Insert one product\n",
            solution: "INSERT INTO products (name, price)\nVALUES ('Notebook', 12.50);",
            tests: [{ type: "contains", value: "INSERT INTO products" }, { type: "contains", value: "(name, price)" }, { type: "contains", value: "'Notebook'" }],
            debuggingTip: "The columns and values must line up in the same order: name gets Notebook, price gets 12.50.",
          },
        },
        {
          id: "sql-module5-l2",
          title: "Changing Rows with UPDATE",
          explanation: "UPDATE changes existing rows. SET chooses the new value, and WHERE chooses which rows are allowed to change. An UPDATE without WHERE changes every row in the table.",
          concept: "UPDATE table\nSET column = value\nWHERE condition;\nAlways inspect the WHERE clause.",
          example: "UPDATE products\nSET price = 15.00\nWHERE id = 42;",
          exercise: {
            prompt: "Change the status of order 17 to 'shipped'.",
            starterCode: "-- Update one order\n",
            solution: "UPDATE orders\nSET status = 'shipped'\nWHERE id = 17;",
            tests: [{ type: "contains", value: "UPDATE orders" }, { type: "contains", value: "SET status = 'shipped'" }, { type: "contains", value: "WHERE id = 17" }],
            debuggingTip: "Pause before running an UPDATE. If WHERE is missing, every order would become shipped.",
          },
        },
        {
          id: "sql-module5-l3",
          title: "Removing Rows with DELETE",
          explanation: "DELETE removes rows that match a WHERE condition. It is powerful and irreversible in many interfaces, so begin with a SELECT using the same WHERE clause whenever the data matters.",
          concept: "DELETE FROM table\nWHERE condition;\nTest the condition with SELECT first.",
          example: "DELETE FROM sessions\nWHERE expires_at < CURRENT_DATE;",
          exercise: {
            prompt: "Delete cancelled orders from orders.",
            starterCode: "-- Remove only cancelled orders\n",
            solution: "DELETE FROM orders\nWHERE status = 'cancelled';",
            tests: [{ type: "contains", value: "DELETE FROM orders" }, { type: "contains", value: "WHERE status = 'cancelled'" }],
            debuggingTip: "DELETE uses FROM after the keyword. Keep WHERE narrow, and preview the affected rows with SELECT first.",
          },
        },
        {
          id: "sql-module5-l4",
          title: "Creating a Table",
          explanation: "CREATE TABLE defines the shape of new data. Each column has a name and a type. A primary key gives every row a stable identity, which later tables can reference.",
          concept: "CREATE TABLE tasks (\n  id INTEGER PRIMARY KEY,\n  title TEXT\n);\nA schema describes the data before rows arrive.",
          example: "CREATE TABLE tasks (\n  id INTEGER PRIMARY KEY,\n  title TEXT NOT NULL,\n  done BOOLEAN\n);",
          exercise: {
            prompt: "Create a notes table with an integer id primary key and a non-null text body column.",
            starterCode: "-- Define the notes table\n",
            solution: "CREATE TABLE notes (\n  id INTEGER PRIMARY KEY,\n  body TEXT NOT NULL\n);",
            tests: [{ type: "contains", value: "CREATE TABLE notes" }, { type: "contains", value: "id INTEGER PRIMARY KEY" }, { type: "contains", value: "body TEXT NOT NULL" }],
            debuggingTip: "Columns inside CREATE TABLE are separated by commas. PRIMARY KEY belongs with the id column definition.",
          },
        },
        {
          id: "sql-module5-l5",
          title: "Constraints Protect Data",
          explanation: "Constraints let the database reject invalid data even when an application has a bug. NOT NULL requires a value, UNIQUE prevents duplicates, and CHECK enforces a rule such as a non-negative price.",
          concept: "email TEXT UNIQUE\nprice DECIMAL CHECK (price >= 0)\nConstraints protect data at its source.",
          example: "CREATE TABLE products (\n  id INTEGER PRIMARY KEY,\n  sku TEXT UNIQUE,\n  price DECIMAL CHECK (price >= 0)\n);",
          exercise: {
            prompt: "Create a coupons table with an id primary key, a unique code, and a discount check that keeps discount at or above zero.",
            starterCode: "-- Add database-level safeguards\n",
            solution: "CREATE TABLE coupons (\n  id INTEGER PRIMARY KEY,\n  code TEXT UNIQUE,\n  discount DECIMAL CHECK (discount >= 0)\n);",
            tests: [{ type: "contains", value: "code TEXT UNIQUE" }, { type: "contains", value: "CHECK (discount >= 0)" }],
            debuggingTip: "A CHECK condition is written in parentheses. It states the values the database will accept, not a message to the user.",
          },
        },
      ],
    },
  ],
};
